import { Mona_Sans } from "next/font/google"
import "./globals.css";
import { Toaster } from "sonner";

const monaSans = Mona_Sans({
  subsets: ["latin"],
  variable: "--font-mona",
})


export const metadata = {
  title: "Spacez",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${monaSans.variable} antialiased scroll-smooth`}
      >
        {children}
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
